import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#0f1419",
        foreground: "#dee3ea",
        "tertiary-container": "#ed8902",
        "on-primary-fixed": "#001d31",
        "error-container": "#93000a",
        "surface-container-lowest": "#0a0f14",
        "outline-variant": "#3e4851",
        "on-tertiary-fixed": "#2d1600",
        "surface-bright": "#353a3f",
        "on-surface": "#dee3ea",
        "on-tertiary": "#4b2800",
        primary: {
          DEFAULT: "#93ccff",
          foreground: "#003351",
        },
        "surface-container-high": "#252a30",
        "on-background": "#dee3ea",
        "surface-variant": "#30353b",
        "surface-tint": "#93ccff",
        "on-error": "#690005",
        "on-primary-container": "#003c5d",
        tertiary: "#ffb875",
        "primary-container": "#00aaff",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#ffb875",
        "on-secondary": "#003544",
        "inverse-surface": "#dee3ea",
        outline: "#88929d",
        "on-primary": "#003351",
        surface: "#0f1419",
        "primary-fixed": "#cce5ff",
        "on-primary-fixed-variant": "#004b73",
        "on-secondary-fixed": "#001f28",
        "surface-container": "#1b2025",
        "surface-container-highest": "#30353b",
        "tertiary-fixed": "#ffdcc0",
        "inverse-primary": "#006398",
        "on-secondary-container": "#005469",
        "secondary-fixed-dim": "#54d5ff",
        "secondary-fixed": "#b8eaff",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#93ccff",
        "on-tertiary-fixed-variant": "#6b3b00",
        "on-surface-variant": "#bec7d3",
        "inverse-on-surface": "#2c3136",
        "secondary-container": "#00cefe",
        secondary: {
          DEFAULT: "#a0e4ff",
          foreground: "#003544",
        },
        "on-secondary-fixed-variant": "#004d61",
        "surface-container-low": "#171c21",
        "surface-dim": "#0f1419",
        "on-tertiary-container": "#562e00",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        full: "9999px",
      },
      spacing: {
        base_unit: "8px",
        card_gap: "12px",
        gutter: "16px",
        container_padding: "24px",
      },
      fontFamily: {
        "label-caps": ["Space Grotesk", "sans-serif"],
        h1: ["Space Grotesk", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-red": {
          "0%": { boxShadow: "0 0 0 0 rgba(239, 68, 68, 0.7)", opacity: "1" },
          "50%": { opacity: "0.5" },
          "70%": { boxShadow: "0 0 0 10px rgba(239, 68, 68, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(239, 68, 68, 0)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-red": "pulse-red 2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
